-- Clean Stream wallet ledger and compliance foundation.
-- This migration is intentionally additive first: profiles.balance remains as a
-- compatibility cache while wallet_balances becomes the source of truth.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.wallet_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  status text not null default 'active'
    check (status in ('active', 'deleted', 'locked')),
  locked_at timestamptz,
  deleted_at timestamptz,
  deletion_acknowledged_at timestamptz,
  deleted_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_loads (
  id bigint generated by default as identity primary key,
  wallet_account_id uuid not null references public.wallet_accounts(id),
  user_id uuid references auth.users(id) on delete set null,
  amount_cents integer not null check (amount_cents > 0),
  paid_amount_cents integer not null check (paid_amount_cents >= 0),
  promo_amount_cents integer not null default 0 check (promo_amount_cents >= 0),
  stripe_payment_intent_id text unique,
  stripe_checkout_session_id text unique,
  stripe_charge_id text unique,
  stripe_event_id text unique,
  status text not null default 'succeeded'
    check (status in ('pending', 'succeeded', 'refunded', 'void')),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_ledger_entries (
  id bigint generated by default as identity primary key,
  wallet_account_id uuid not null references public.wallet_accounts(id),
  entry_type text not null check (
    entry_type in (
      'legacy_balance',
      'load_paid',
      'load_bonus',
      'redeem_paid',
      'redeem_bonus',
      'admin_adjustment',
      'legal_cash_redemption',
      'stripe_refund',
      'void'
    )
  ),
  amount_cents integer not null,
  paid_amount_cents integer not null default 0,
  promo_amount_cents integer not null default 0,
  wallet_load_id bigint references public.wallet_loads(id),
  stripe_payment_intent_id text,
  stripe_charge_id text,
  stripe_refund_id text,
  machine_id bigint references public."Machines"(id) on delete set null,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint wallet_ledger_amount_split_matches check (
    amount_cents = paid_amount_cents + promo_amount_cents
  )
);

create table if not exists public.wallet_redemptions (
  id bigint generated by default as identity primary key,
  wallet_account_id uuid not null references public.wallet_accounts(id),
  user_id uuid references auth.users(id) on delete set null,
  machine_id bigint references public."Machines"(id) on delete set null,
  amount_cents integer not null check (amount_cents > 0),
  paid_amount_cents integer not null default 0 check (paid_amount_cents >= 0),
  promo_amount_cents integer not null default 0 check (promo_amount_cents >= 0),
  status text not null default 'succeeded'
    check (status in ('succeeded', 'void')),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.deleted_account_complaints (
  id bigint generated by default as identity primary key,
  wallet_account_id uuid not null references public.wallet_accounts(id),
  complaint_note text not null,
  resolution text not null default 'denied'
    check (resolution in ('denied', 'legal_cash_redemption', 'other_required_remedy')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists wallet_accounts_user_id_idx
  on public.wallet_accounts(user_id);
create index if not exists wallet_accounts_status_idx
  on public.wallet_accounts(status);
create index if not exists wallet_ledger_wallet_created_idx
  on public.wallet_ledger_entries(wallet_account_id, created_at desc);
create index if not exists wallet_loads_wallet_created_idx
  on public.wallet_loads(wallet_account_id, created_at desc);
create index if not exists wallet_redemptions_wallet_created_idx
  on public.wallet_redemptions(wallet_account_id, created_at desc);
create index if not exists wallet_complaints_wallet_created_idx
  on public.deleted_account_complaints(wallet_account_id, created_at desc);

create index if not exists transactions_user_id_idx
  on public.transactions(user_id);
create index if not exists refunds_user_id_idx
  on public."Refunds"(user_id);
create index if not exists refunds_transaction_id_idx
  on public."Refunds"(transaction_id);
create index if not exists machines_location_id_idx
  on public."Machines"("Location_ID");
create index if not exists location_to_admin_location_id_idx
  on public."Location_to_Admin"(location_id);
create index if not exists location_to_admin_user_id_idx
  on public."Location_to_Admin"(user_id);

create or replace view public.wallet_balances
with (security_invoker = true) as
select
  wa.id as wallet_account_id,
  wa.user_id,
  wa.status,
  coalesce(sum(wle.paid_amount_cents), 0)::integer as paid_balance_cents,
  coalesce(sum(wle.promo_amount_cents), 0)::integer as promo_balance_cents,
  coalesce(sum(wle.amount_cents), 0)::integer as total_balance_cents
from public.wallet_accounts wa
left join public.wallet_ledger_entries wle
  on wle.wallet_account_id = wa.id
group by wa.id, wa.user_id, wa.status;

create or replace function public.is_admin_or_owner()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.roles in ('Admin'::"Roles", 'Owner'::"Roles")
  );
$$;

create or replace function public.get_or_create_wallet_account(target_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id uuid;
begin
  if target_user_id is null then
    raise exception 'Missing user id';
  end if;

  select id into wallet_id
  from public.wallet_accounts
  where user_id = target_user_id;

  if wallet_id is null then
    insert into public.wallet_accounts(user_id)
    values (target_user_id)
    on conflict (user_id) do update
      set updated_at = now()
    returning id into wallet_id;
  end if;

  return wallet_id;
end;
$$;

create or replace function public.sync_profile_wallet_balance(wallet_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user_id uuid;
  total_cents integer;
begin
  select user_id, total_balance_cents
    into target_user_id, total_cents
  from public.wallet_balances
  where wallet_account_id = wallet_id;

  if target_user_id is not null then
    update public.profiles
    set balance = coalesce(total_cents, 0)::numeric / 100.0
    where id = target_user_id;
  end if;
end;
$$;

create or replace function public.record_wallet_load_from_stripe(
  target_user_id uuid,
  amount_cents integer,
  stripe_payment_intent_id text default null,
  stripe_checkout_session_id text default null,
  stripe_charge_id text default null,
  stripe_event_id text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id uuid;
  load_id bigint;
  existing_wallet_id uuid;
  reward_before_cents integer;
  combined_cents integer;
  bonus_count integer;
  bonus_cents integer;
  remainder_cents integer;
begin
  if target_user_id is null or amount_cents is null or amount_cents <= 0 then
    raise exception 'Invalid wallet load';
  end if;

  select wl.wallet_account_id into existing_wallet_id
  from public.wallet_loads wl
  where (stripe_payment_intent_id is not null and wl.stripe_payment_intent_id = record_wallet_load_from_stripe.stripe_payment_intent_id)
     or (stripe_checkout_session_id is not null and wl.stripe_checkout_session_id = record_wallet_load_from_stripe.stripe_checkout_session_id)
     or (stripe_event_id is not null and wl.stripe_event_id = record_wallet_load_from_stripe.stripe_event_id)
  limit 1;

  if existing_wallet_id is not null then
    return existing_wallet_id;
  end if;

  wallet_id := public.get_or_create_wallet_account(target_user_id);

  select coalesce(round(reward_tracker * 100), 0)::integer
    into reward_before_cents
  from public.profiles
  where id = target_user_id;

  combined_cents := coalesce(reward_before_cents, 0) + amount_cents;
  bonus_count := combined_cents / 2000;
  bonus_cents := bonus_count * 500;
  remainder_cents := combined_cents % 2000;

  insert into public.wallet_loads(
    wallet_account_id,
    user_id,
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    stripe_payment_intent_id,
    stripe_checkout_session_id,
    stripe_charge_id,
    stripe_event_id,
    status,
    note
  )
  values (
    wallet_id,
    target_user_id,
    amount_cents,
    amount_cents,
    bonus_cents,
    stripe_payment_intent_id,
    stripe_checkout_session_id,
    stripe_charge_id,
    stripe_event_id,
    'succeeded',
    'Stripe wallet load'
  )
  returning id into load_id;

  insert into public.wallet_ledger_entries(
    wallet_account_id,
    entry_type,
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    wallet_load_id,
    stripe_payment_intent_id,
    stripe_charge_id,
    note
  )
  values (
    wallet_id,
    'load_paid',
    amount_cents,
    amount_cents,
    0,
    load_id,
    stripe_payment_intent_id,
    stripe_charge_id,
    'Paid loyalty card load'
  );

  if bonus_cents > 0 then
    insert into public.wallet_ledger_entries(
      wallet_account_id,
      entry_type,
      amount_cents,
      paid_amount_cents,
      promo_amount_cents,
      wallet_load_id,
      stripe_payment_intent_id,
      stripe_charge_id,
      note
    )
    values (
      wallet_id,
      'load_bonus',
      bonus_cents,
      0,
      bonus_cents,
      load_id,
      stripe_payment_intent_id,
      stripe_charge_id,
      'Promotional loyalty reward credit'
    );
  end if;

  update public.profiles
  set reward_tracker = remainder_cents::numeric / 100.0
  where id = target_user_id;

  perform public.sync_profile_wallet_balance(wallet_id);

  return wallet_id;
end;
$$;

create or replace function public.redeem_wallet_for_machine(
  target_user_id uuid,
  target_machine_id bigint,
  amount_cents integer,
  redemption_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id uuid;
  paid_balance integer;
  promo_balance integer;
  promo_debit integer;
  paid_debit integer;
  redemption_id bigint;
begin
  if target_user_id is null or auth.uid() <> target_user_id then
    raise exception 'Unauthorized';
  end if;

  if amount_cents is null or amount_cents <= 0 then
    raise exception 'Invalid amount';
  end if;

  wallet_id := public.get_or_create_wallet_account(target_user_id);

  select paid_balance_cents, promo_balance_cents
    into paid_balance, promo_balance
  from public.wallet_balances
  where wallet_account_id = wallet_id;

  if coalesce(paid_balance, 0) + coalesce(promo_balance, 0) < amount_cents then
    raise exception 'Insufficient balance';
  end if;

  promo_debit := least(coalesce(promo_balance, 0), amount_cents);
  paid_debit := amount_cents - promo_debit;

  insert into public.wallet_redemptions(
    wallet_account_id,
    user_id,
    machine_id,
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    status,
    note
  )
  values (
    wallet_id,
    target_user_id,
    target_machine_id,
    amount_cents,
    paid_debit,
    promo_debit,
    'succeeded',
    redemption_note
  )
  returning id into redemption_id;

  if promo_debit > 0 then
    insert into public.wallet_ledger_entries(
      wallet_account_id,
      entry_type,
      amount_cents,
      paid_amount_cents,
      promo_amount_cents,
      machine_id,
      note
    )
    values (
      wallet_id,
      'redeem_bonus',
      -promo_debit,
      0,
      -promo_debit,
      target_machine_id,
      redemption_note
    );
  end if;

  if paid_debit > 0 then
    insert into public.wallet_ledger_entries(
      wallet_account_id,
      entry_type,
      amount_cents,
      paid_amount_cents,
      promo_amount_cents,
      machine_id,
      note
    )
    values (
      wallet_id,
      'redeem_paid',
      -paid_debit,
      -paid_debit,
      0,
      target_machine_id,
      redemption_note
    );
  end if;

  perform public.sync_profile_wallet_balance(wallet_id);

  return jsonb_build_object(
    'wallet_account_id', wallet_id,
    'redemption_id', redemption_id,
    'paid_debit_cents', paid_debit,
    'promo_debit_cents', promo_debit
  );
end;
$$;

create or replace function public.admin_adjust_wallet(
  wallet_id uuid,
  amount_cents integer,
  paid_amount_cents integer,
  promo_amount_cents integer,
  adjustment_note text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  entry_id bigint;
begin
  if not public.is_admin_or_owner() then
    raise exception 'Unauthorized';
  end if;

  if adjustment_note is null or btrim(adjustment_note) = '' then
    raise exception 'Admin note required';
  end if;

  insert into public.wallet_ledger_entries(
    wallet_account_id,
    entry_type,
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    note,
    created_by
  )
  values (
    wallet_id,
    'admin_adjustment',
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    adjustment_note,
    auth.uid()
  )
  returning id into entry_id;

  perform public.sync_profile_wallet_balance(wallet_id);
  return entry_id;
end;
$$;

create or replace function public.admin_set_wallet_status(
  wallet_id uuid,
  new_status text,
  status_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin_or_owner() then
    raise exception 'Unauthorized';
  end if;

  if new_status not in ('active', 'locked') then
    raise exception 'Invalid admin wallet status';
  end if;

  update public.wallet_accounts
  set
    status = new_status,
    locked_at = case when new_status = 'locked' then now() else null end,
    updated_at = now()
  where id = wallet_id;
end;
$$;

create or replace function public.record_deleted_account_complaint(
  wallet_id uuid,
  complaint_note text,
  resolution text default 'denied'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  complaint_id bigint;
begin
  if not public.is_admin_or_owner() then
    raise exception 'Unauthorized';
  end if;

  if complaint_note is null or btrim(complaint_note) = '' then
    raise exception 'Complaint note required';
  end if;

  insert into public.deleted_account_complaints(
    wallet_account_id,
    complaint_note,
    resolution,
    created_by
  )
  values (
    wallet_id,
    complaint_note,
    resolution,
    auth.uid()
  )
  returning id into complaint_id;

  return complaint_id;
end;
$$;

create or replace function public.admin_record_legal_cash_redemption(
  wallet_id uuid,
  amount_cents integer,
  stripe_refund_id text default null,
  redemption_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  entry_id bigint;
begin
  if not public.is_admin_or_owner() then
    raise exception 'Unauthorized';
  end if;

  if amount_cents is null or amount_cents <= 0 then
    raise exception 'Invalid amount';
  end if;

  if redemption_note is null or btrim(redemption_note) = '' then
    raise exception 'Admin note required';
  end if;

  insert into public.wallet_ledger_entries(
    wallet_account_id,
    entry_type,
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    stripe_refund_id,
    note,
    created_by
  )
  values (
    wallet_id,
    case when stripe_refund_id is null then 'legal_cash_redemption' else 'stripe_refund' end,
    -amount_cents,
    -amount_cents,
    0,
    stripe_refund_id,
    redemption_note,
    auth.uid()
  )
  returning id into entry_id;

  perform public.sync_profile_wallet_balance(wallet_id);
  return entry_id;
end;
$$;

create or replace function public.anonymize_wallet_for_deleted_user(
  target_user_id uuid,
  deletion_note text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id uuid;
begin
  if target_user_id is null then
    raise exception 'Missing user id';
  end if;

  wallet_id := public.get_or_create_wallet_account(target_user_id);

  update public.wallet_accounts
  set
    user_id = null,
    status = 'deleted',
    deleted_at = now(),
    deletion_acknowledged_at = now(),
    deleted_reason = deletion_note,
    updated_at = now()
  where id = wallet_id;

  update public.wallet_loads
  set user_id = null
  where wallet_account_id = wallet_id;

  update public.wallet_redemptions
  set user_id = null
  where wallet_account_id = wallet_id;

  return wallet_id;
end;
$$;

-- Backfill existing profile balances as legacy paid wallet value.
insert into public.wallet_accounts(user_id)
select p.id
from public.profiles p
where not exists (
  select 1 from public.wallet_accounts wa where wa.user_id = p.id
);

insert into public.wallet_ledger_entries(
  wallet_account_id,
  entry_type,
  amount_cents,
  paid_amount_cents,
  promo_amount_cents,
  note
)
select
  wa.id,
  'legacy_balance',
  coalesce(round(p.balance * 100), 0)::integer,
  coalesce(round(p.balance * 100), 0)::integer,
  0,
  'Legacy profiles.balance backfill'
from public.profiles p
join public.wallet_accounts wa on wa.user_id = p.id
where coalesce(p.balance, 0) <> 0
  and not exists (
    select 1
    from public.wallet_ledger_entries wle
    where wle.wallet_account_id = wa.id
      and wle.entry_type = 'legacy_balance'
  );

alter table public.wallet_accounts enable row level security;
alter table public.wallet_loads enable row level security;
alter table public.wallet_ledger_entries enable row level security;
alter table public.wallet_redemptions enable row level security;
alter table public.deleted_account_complaints enable row level security;

drop policy if exists "Users can read own wallet accounts" on public.wallet_accounts;
create policy "Users can read own wallet accounts"
on public.wallet_accounts
for select
using (user_id = (select auth.uid()) or public.is_admin_or_owner());

drop policy if exists "Users can read own wallet loads" on public.wallet_loads;
create policy "Users can read own wallet loads"
on public.wallet_loads
for select
using (
  exists (
    select 1 from public.wallet_accounts wa
    where wa.id = wallet_loads.wallet_account_id
      and (wa.user_id = (select auth.uid()) or public.is_admin_or_owner())
  )
);

drop policy if exists "Users can read own wallet ledger" on public.wallet_ledger_entries;
create policy "Users can read own wallet ledger"
on public.wallet_ledger_entries
for select
using (
  exists (
    select 1 from public.wallet_accounts wa
    where wa.id = wallet_ledger_entries.wallet_account_id
      and (wa.user_id = (select auth.uid()) or public.is_admin_or_owner())
  )
);

drop policy if exists "Users can read own wallet redemptions" on public.wallet_redemptions;
create policy "Users can read own wallet redemptions"
on public.wallet_redemptions
for select
using (
  exists (
    select 1 from public.wallet_accounts wa
    where wa.id = wallet_redemptions.wallet_account_id
      and (wa.user_id = (select auth.uid()) or public.is_admin_or_owner())
  )
);

drop policy if exists "Admins can read deleted account complaints" on public.deleted_account_complaints;
create policy "Admins can read deleted account complaints"
on public.deleted_account_complaints
for select
using (public.is_admin_or_owner());

-- Tighten existing high-risk policies while keeping user profile edits working.
drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles
for insert
with check (id = (select auth.uid()));

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
on public.profiles
for select
using (id = (select auth.uid()) or public.is_admin_or_owner());

drop policy if exists "Users can view their own transactions" on public.transactions;
create policy "Users can view their own transactions"
on public.transactions
for select
using (user_id = (select auth.uid()) or public.is_admin_or_owner());

drop policy if exists "Allow Update" on public.transactions;

-- Column-level hardening for money-like/profile authority fields.
revoke update (balance, reward_tracker, roles) on public.profiles from anon, authenticated;

-- Function hardening flagged by Supabase advisors.
create or replace function public.sync_profile_email()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.profiles
  set email = new.email
  where id = new.id;
  return new;
end;
$$;

create or replace function public.increment_user_refund_attempts(uid uuid)
returns void
language plpgsql
set search_path = public
as $$
begin
  update public.profiles
  set refund_attempts = refund_attempts + 1
  where id = uid;
end;
$$;

create or replace function public.update_user_balance()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.type = 'credit' then
    update public.profiles
    set balance = balance + new.amount
    where id = new.user_id;
  elsif new.type = 'debit' then
    update public.profiles
    set balance = balance - new.amount
    where id = new.user_id;
  end if;
  return new;
end;
$$;

create or replace function public.update_balance()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.profiles
  set balance = balance + new.amount
  where id = new.user_id;
  return new;
end;
$$;

create or replace function public.notify_new_refund()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  perform pg_notify('new_refund', row_to_json(new)::text);
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.increment_loyalty_balance(uuid, numeric) from public, anon, authenticated;
revoke execute on function public.notify_new_refund() from public, anon, authenticated;
revoke execute on function public.sync_user_full_name() from public, anon, authenticated;
revoke execute on function public.get_or_create_wallet_account(uuid) from public, anon, authenticated;
revoke execute on function public.sync_profile_wallet_balance(uuid) from public, anon, authenticated;
revoke execute on function public.record_wallet_load_from_stripe(uuid, integer, text, text, text, text) from public, anon, authenticated;
revoke execute on function public.is_admin_or_owner() from public, anon;
revoke execute on function public.redeem_wallet_for_machine(uuid, bigint, integer, text) from public, anon;
revoke execute on function public.admin_adjust_wallet(uuid, integer, integer, integer, text) from public, anon;
revoke execute on function public.admin_set_wallet_status(uuid, text, text) from public, anon;
revoke execute on function public.record_deleted_account_complaint(uuid, text, text) from public, anon;
revoke execute on function public.admin_record_legal_cash_redemption(uuid, integer, text, text) from public, anon;
grant execute on function public.redeem_wallet_for_machine(uuid, bigint, integer, text) to authenticated;
grant execute on function public.admin_adjust_wallet(uuid, integer, integer, integer, text) to authenticated;
grant execute on function public.admin_set_wallet_status(uuid, text, text) to authenticated;
grant execute on function public.record_deleted_account_complaint(uuid, text, text) to authenticated;
grant execute on function public.admin_record_legal_cash_redemption(uuid, integer, text, text) to authenticated;
revoke execute on function public.anonymize_wallet_for_deleted_user(uuid, text) from public, anon, authenticated;
