-- Cortina StaticQR pricing, device mapping, and vend audit foundation.

create extension if not exists pgcrypto with schema extensions;

create table public.washer_size_rates (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public."Locations"(id) on delete cascade,
  size_label text not null check (btrim(size_label) <> ''),
  capacity_kg bigint not null check (capacity_kg > 0),
  price_cents integer not null check (price_cents > 0),
  is_active boolean not null default true,
  review_required boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint washer_size_rates_location_label_key unique (location_id, size_label)
);

alter table public."Machines"
  add column washer_size_rate_id bigint
  references public.washer_size_rates(id) on delete restrict;

create table public.cortina_machine_config (
  machine_id bigint primary key references public."Machines"(id) on delete cascade,
  public_machine_token uuid not null default gen_random_uuid() unique,
  nayax_terminal_id text,
  nayax_uniqr text,
  pulse_line_number integer check (pulse_line_number > 0),
  environment text not null default 'sandbox'
    check (environment in ('sandbox', 'production')),
  is_enabled boolean not null default false,
  review_required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cortina_machine_identifier_required check (
    not is_enabled or (
      (nullif(btrim(nayax_terminal_id), '') is not null or
       nullif(btrim(nayax_uniqr), '') is not null)
      and pulse_line_number is not null
      and not review_required
    )
  )
);

create unique index cortina_machine_terminal_id_key
  on public.cortina_machine_config(nayax_terminal_id)
  where nayax_terminal_id is not null;
create unique index cortina_machine_uniqr_key
  on public.cortina_machine_config(nayax_uniqr)
  where nayax_uniqr is not null;

create table public.cortina_vend_sessions (
  id uuid primary key default gen_random_uuid(),
  client_request_id uuid not null unique,
  client_access_token_hash text not null unique,
  machine_id bigint not null references public."Machines"(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  washer_size_rate_id bigint references public.washer_size_rates(id) on delete set null,
  amount_cents integer not null check (amount_cents > 0),
  dryer_minutes integer check (dryer_minutes is null or dryer_minutes between 5 and 90),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  payment_method text not null check (payment_method in ('card', 'wallet')),
  channel text not null check (channel in ('app', 'web')),
  status text not null default 'payment_pending' check (
    status in (
      'payment_pending', 'paid', 'starting', 'awaiting_sale', 'approved',
      'started', 'voided', 'refunded', 'failed', 'timed_out',
      'support_required'
    )
  ),
  transaction_id text not null unique check (char_length(transaction_id) between 8 and 40),
  stripe_payment_intent_id text unique,
  stripe_checkout_session_id text unique,
  stripe_charge_id text,
  stripe_refund_id text,
  wallet_redemption_id bigint unique references public.wallet_redemptions(id),
  nayax_transaction_id text,
  nayax_rrn text,
  failure_code text,
  failure_message text,
  start_requested_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cortina_vend_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.cortina_vend_sessions(id) on delete cascade,
  source text not null check (source in ('clean_stream', 'stripe', 'nayax')),
  event_type text not null,
  event_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index washer_size_rates_location_idx
  on public.washer_size_rates(location_id);
create index machines_washer_size_rate_idx
  on public."Machines"(washer_size_rate_id);
create index cortina_sessions_machine_created_idx
  on public.cortina_vend_sessions(machine_id, created_at desc);
create index cortina_sessions_user_created_idx
  on public.cortina_vend_sessions(user_id, created_at desc);
create index cortina_sessions_status_created_idx
  on public.cortina_vend_sessions(status, created_at);
create index cortina_events_session_created_idx
  on public.cortina_vend_events(session_id, created_at);

create or replace function public.set_cortina_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger washer_size_rates_updated_at
before update on public.washer_size_rates
for each row execute function public.set_cortina_updated_at();

create trigger cortina_machine_config_updated_at
before update on public.cortina_machine_config
for each row execute function public.set_cortina_updated_at();

create trigger cortina_vend_sessions_updated_at
before update on public.cortina_vend_sessions
for each row execute function public.set_cortina_updated_at();

-- Preserve existing washer prices while moving each location/size/price
-- combination into a managed rate that must be reviewed before Cortina use.
with legacy_prices as (
  select distinct
    m."Location_ID" as location_id,
    m."Weight_kg" as capacity_kg,
    round(m."Price" * 100)::integer as price_cents
  from public."Machines" m
  where lower(coalesce(m."Machine_type", '')) = 'washer'
    and m."Location_ID" is not null
    and m."Weight_kg" is not null
    and m."Weight_kg" > 0
    and m."Price" is not null
    and m."Price" > 0
), legacy_price_counts as (
  select location_id, capacity_kg, count(*) as price_count
  from legacy_prices
  group by location_id, capacity_kg
)
insert into public.washer_size_rates (
  location_id,
  size_label,
  capacity_kg,
  price_cents,
  review_required
)
select
  legacy.location_id,
  case
    when counts.price_count = 1 then legacy.capacity_kg || ' kg'
    else legacy.capacity_kg || ' kg - legacy $' ||
      to_char(legacy.price_cents::numeric / 100, 'FM999999990.00')
  end,
  legacy.capacity_kg,
  legacy.price_cents,
  true
from legacy_prices legacy
join legacy_price_counts counts
  using (location_id, capacity_kg)
on conflict (location_id, size_label) do nothing;

update public."Machines" m
set washer_size_rate_id = rate.id
from public.washer_size_rates rate
where lower(coalesce(m."Machine_type", '')) = 'washer'
  and rate.location_id = m."Location_ID"
  and rate.capacity_kg = m."Weight_kg"
  and rate.price_cents = round(m."Price" * 100)::integer;

insert into public.cortina_machine_config(machine_id)
select id from public."Machines"
on conflict (machine_id) do nothing;

create or replace function public.apply_washer_size_rate_to_machine()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  selected_rate public.washer_size_rates%rowtype;
begin
  if lower(coalesce(new."Machine_type", '')) <> 'washer' then
    if new.washer_size_rate_id is not null then
      raise exception 'Only washers may use a washer size rate';
    end if;
    return new;
  end if;

  if new.washer_size_rate_id is null then
    return new;
  end if;

  select * into selected_rate
  from public.washer_size_rates
  where id = new.washer_size_rate_id;

  if not found or selected_rate.location_id is distinct from new."Location_ID" then
    raise exception 'Washer size rate must belong to the machine location';
  end if;

  if tg_op = 'INSERT' or new.washer_size_rate_id is distinct from old.washer_size_rate_id then
    if not selected_rate.is_active then
      raise exception 'Inactive washer size rate cannot be assigned';
    end if;
  end if;

  new."Weight_kg" := selected_rate.capacity_kg;
  new."Price" := selected_rate.price_cents::double precision / 100.0;
  return new;
end;
$$;

create trigger apply_washer_size_rate_to_machine
before insert or update of washer_size_rate_id, "Location_ID", "Machine_type", "Price", "Weight_kg"
on public."Machines"
for each row execute function public.apply_washer_size_rate_to_machine();

create or replace function public.create_cortina_machine_config()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.cortina_machine_config (machine_id)
  values (new.id)
  on conflict (machine_id) do nothing;
  return new;
end;
$$;

revoke all on function public.create_cortina_machine_config()
from public, anon, authenticated;

create trigger create_machine_cortina_config
after insert on public."Machines"
for each row execute function public.create_cortina_machine_config();

create or replace function public.sync_washer_rate_to_machines()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public."Machines"
  set
    "Price" = new.price_cents::double precision / 100.0,
    "Weight_kg" = new.capacity_kg
  where washer_size_rate_id = new.id;
  return new;
end;
$$;

create trigger sync_washer_rate_to_machines
after update of price_cents, capacity_kg on public.washer_size_rates
for each row execute function public.sync_washer_rate_to_machines();

alter table public.washer_size_rates enable row level security;
alter table public.cortina_machine_config enable row level security;
alter table public.cortina_vend_sessions enable row level security;
alter table public.cortina_vend_events enable row level security;

create policy washer_rates_location_admin_select
on public.washer_size_rates for select to authenticated
using (
  exists (
    select 1
    from public."Location_to_Admin" lta
    join public.profiles p on p.id = lta.user_id
    where lta.location_id = washer_size_rates.location_id
      and lta.user_id = (select auth.uid())
      and p.roles in ('Admin'::public."Roles", 'Owner'::public."Roles")
  )
);

create policy washer_rates_location_owner_write
on public.washer_size_rates for all to authenticated
using (
  exists (
    select 1
    from public."Location_to_Admin" lta
    join public.profiles p on p.id = lta.user_id
    where lta.location_id = washer_size_rates.location_id
      and lta.user_id = (select auth.uid())
      and p.roles = 'Owner'::public."Roles"
  )
)
with check (
  exists (
    select 1
    from public."Location_to_Admin" lta
    join public.profiles p on p.id = lta.user_id
    where lta.location_id = washer_size_rates.location_id
      and lta.user_id = (select auth.uid())
      and p.roles = 'Owner'::public."Roles"
  )
);

create policy cortina_config_location_admin_select
on public.cortina_machine_config for select to authenticated
using (
  exists (
    select 1
    from public."Machines" m
    join public."Location_to_Admin" lta on lta.location_id = m."Location_ID"
    join public.profiles p on p.id = lta.user_id
    where m.id = cortina_machine_config.machine_id
      and lta.user_id = (select auth.uid())
      and p.roles in ('Admin'::public."Roles", 'Owner'::public."Roles")
  )
);

create policy cortina_config_location_owner_write
on public.cortina_machine_config for all to authenticated
using (
  exists (
    select 1
    from public."Machines" m
    join public."Location_to_Admin" lta on lta.location_id = m."Location_ID"
    join public.profiles p on p.id = lta.user_id
    where m.id = cortina_machine_config.machine_id
      and lta.user_id = (select auth.uid())
      and p.roles = 'Owner'::public."Roles"
  )
)
with check (
  exists (
    select 1
    from public."Machines" m
    join public."Location_to_Admin" lta on lta.location_id = m."Location_ID"
    join public.profiles p on p.id = lta.user_id
    where m.id = cortina_machine_config.machine_id
      and lta.user_id = (select auth.uid())
      and p.roles = 'Owner'::public."Roles"
  )
);

grant select, insert, update, delete on public.washer_size_rates to authenticated;
grant select, insert, update, delete on public.cortina_machine_config to authenticated;
grant usage, select on sequence public.washer_size_rates_id_seq to authenticated;
revoke all on public.cortina_vend_sessions from anon, authenticated;
revoke all on public.cortina_vend_events from anon, authenticated;

create or replace function public.reverse_cortina_wallet_redemption(
  target_session_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_session public.cortina_vend_sessions%rowtype;
  target_redemption public.wallet_redemptions%rowtype;
begin
  select * into target_session
  from public.cortina_vend_sessions
  where id = target_session_id
  for update;

  if not found or target_session.payment_method <> 'wallet' or
     target_session.wallet_redemption_id is null then
    raise exception 'Wallet vend session not found';
  end if;

  select * into target_redemption
  from public.wallet_redemptions
  where id = target_session.wallet_redemption_id
  for update;

  if target_redemption.status = 'void' then
    return false;
  end if;

  insert into public.wallet_ledger_entries (
    wallet_account_id,
    entry_type,
    amount_cents,
    paid_amount_cents,
    promo_amount_cents,
    machine_id,
    note
  ) values (
    target_redemption.wallet_account_id,
    'void',
    target_redemption.amount_cents,
    target_redemption.paid_amount_cents,
    target_redemption.promo_amount_cents,
    target_redemption.machine_id,
    'Cortina vend reversal for session ' || target_session_id
  );

  update public.wallet_redemptions
  set status = 'void'
  where id = target_redemption.id;

  perform public.sync_profile_wallet_balance(target_redemption.wallet_account_id);

  update public.cortina_vend_sessions
  set status = 'refunded', completed_at = now()
  where id = target_session_id;

  return true;
end;
$$;

revoke all on function public.reverse_cortina_wallet_redemption(uuid)
  from public, anon, authenticated;
grant execute on function public.reverse_cortina_wallet_redemption(uuid)
  to service_role;

create or replace function public.redeem_wallet_for_cortina(
  target_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_session public.cortina_vend_sessions%rowtype;
  redemption jsonb;
begin
  select * into target_session
  from public.cortina_vend_sessions
  where id = target_session_id
  for update;

  if not found or target_session.payment_method <> 'wallet' or
     target_session.status <> 'payment_pending' then
    raise exception 'Wallet vend session is not payable';
  end if;

  if target_session.user_id is null or
     target_session.user_id is distinct from (select auth.uid()) then
    raise exception 'Unauthorized';
  end if;

  redemption := public.redeem_wallet_for_machine(
    target_session.user_id,
    target_session.machine_id,
    target_session.amount_cents,
    'Cortina vend ' || target_session.id
  );

  update public.cortina_vend_sessions
  set
    status = 'paid',
    wallet_redemption_id = (redemption->>'redemption_id')::bigint
  where id = target_session.id;

  return redemption;
end;
$$;

revoke all on function public.redeem_wallet_for_cortina(uuid)
  from public, anon;
grant execute on function public.redeem_wallet_for_cortina(uuid)
  to authenticated;
